-- AUTOGENERATED CODE BY export_accountitems.lua

ENTITLEMENTLOOKUPS = {
	PSN = {},
}

ENTITLEMENTLOOKUPS.PSN["WELCOM"] = "pack_boomerang_psn"
ENTITLEMENTLOOKUPS.PSN["FANTAS"] = "pack_fantasy_items"
ENTITLEMENTLOOKUPS.PSN["FORGWP"] = "pack_forge_weapons"
ENTITLEMENTLOOKUPS.PSN["DXWAND"] = "pack_wanda_deluxe"
ENTITLEMENTLOOKUPS.PSN["DXWORM"] = "pack_wormwood_deluxe"
ENTITLEMENTLOOKUPS.PSN["DXWORT"] = "pack_wortox_deluxe"
ENTITLEMENTLOOKUPS.PSN["DXWURT"] = "pack_wurt_deluxe"
