-- AUTOGENERATED CODE BY export_accountitems.lua

IDLEANIMATIONS_ITEMS =
{
	idleanimations_wx78_headadjust =
	{
		rarity = "Loyal",
		type = "idleanimations",
		skin_tags = { "IDLEANIMATIONS", },
		data =
		{
			item_type = "idleanimations_wx78_headadjust",
			requires_validation = true,
			anim = "idle_wx78_headadjust",
		},
		release_group = 182,
	},
}

