-- AUTOGENERATED CODE BY export_accountitems.lua

PREFAB_SKINS = {
	abigail =
	{
		"abigail_ancient",
		"abigail_creepy",
		"abigail_formal",
		"abigail_funeral",
		"abigail_gladiator",
		"abigail_handmedown",
		"abigail_ice",
		"abigail_lunar",
		"abigail_lureplant",
		"abigail_magma",
		"abigail_masquerade",
		"abigail_nature",
		"abigail_pirate",
		"abigail_rose",
		"abigail_shadow",
		"abigail_survivor",
		"abigail_victorian",
		"abigail_yule",
	},
	abigail_flower =
	{
		"abigail_flower_ancient",
		"abigail_flower_creepy",
		"abigail_flower_formal",
		"abigail_flower_funeral",
		"abigail_flower_gladiator",
		"abigail_flower_handmedown",
		"abigail_flower_ice",
		"abigail_flower_lunar",
		"abigail_flower_lureplant",
		"abigail_flower_magma",
		"abigail_flower_masquerade",
		"abigail_flower_nature",
		"abigail_flower_pirate",
		"abigail_flower_rose",
		"abigail_flower_shadow",
		"abigail_flower_survivor",
		"abigail_flower_victorian",
		"abigail_flower_yule",
	},
	alterguardianhat =
	{
		"alterguardianhat_lastprism",
	},
	amulet =
	{
		"amulet_red_heart",
		"amulet_red_occulteye",
		"amulet_red_relic",
		"amulet_red_rose",
	},
	anchor =
	{
		"anchor_nautical",
	},
	anchor_item =
	{
		"anchor_nautical_item",
	},
	antlionhat =
	{
		"hat_antlion_swamp",
	},
	armor_bramble =
	{
		"armor_bramble_ancient",
	},
	armor_lunarplant =
	{
		"armor_lunarplant_brave",
		"armor_lunarplant_knight",
	},
	armor_lunarplant_husk =
	{
		"armor_lunarplant_husk_brave",
		"armor_lunarplant_husk_knight",
	},
	armor_sanity =
	{
		"armor_sanity_curve",
		"armor_sanity_sharp",
		"armor_sanity_wizard",
	},
	armordragonfly =
	{
		"armor_dragonfly_fangedcollar",
		"armor_dragonfly_haramaki",
		"armor_dragonfly_lamellar",
		"armor_dragonfly_roman",
	},
	armordreadstone =
	{
		"armor_dreadstone_horn",
	},
	armorgrass =
	{
		"armor_grass_cloak",
		"armor_grass_woven",
	},
	armormarble =
	{
		"armor_marble_chainmail",
		"armor_marble_planet",
		"armor_marble_rockabs",
		"armor_marble_valkyrie",
	},
	armorruins =
	{
		"armor_ruins_an",
		"armor_ruins_arcane",
		"armor_ruins_bulky",
		"armor_ruins_leaf",
		"armor_ruins_tusk",
	},
	armorskeleton =
	{
		"armor_skeleton_mythical",
		"armor_skeleton_relic",
		"armor_skeleton_shadowscalemail",
	},
	armorwood =
	{
		"armor_wood_fangedcollar",
		"armor_wood_haramaki",
		"armor_wood_lamellar",
		"armor_wood_roman",
	},
	arrowsign_post =
	{
		"arrowsign_post_circus",
		"arrowsign_post_factory",
		"arrowsign_post_fantasy",
	},
	axe =
	{
		"axe_feathered",
		"axe_heart",
		"axe_invisible",
		"axe_northern",
		"axe_victorian",
	},
	backpack =
	{
		"backpack_babybeef",
		"backpack_basic_blue_catcoon",
		"backpack_basic_green_olive",
		"backpack_bat",
		"backpack_beefalo",
		"backpack_buckle_grey_pewter",
		"backpack_buckle_navy_phthalo",
		"backpack_buckle_red_rook",
		"backpack_camping_green_viridian",
		"backpack_camping_orange_carrot",
		"backpack_camping_red_koalefant",
		"backpack_carrat",
		"backpack_catcoon",
		"backpack_catcoonp",
		"backpack_chester",
		"backpack_crab",
		"backpack_crab_resurrected",
		"backpack_deerclops",
		"backpack_deerclops_resurrected",
		"backpack_dragonfly_fire",
		"backpack_glommer",
		"backpack_glommer_resurrected",
		"backpack_heart",
		"backpack_hound",
		"backpack_koalefant",
		"backpack_labrat",
		"backpack_mandrake",
		"backpack_mandrake_resurrected",
		"backpack_mushy",
		"backpack_poop",
		"backpack_rabbit",
		"backpack_smallbird",
		"backpack_spider",
		"backpack_splumonkey",
	},
	batbat =
	{
		"batbat_fantasy",
		"batbat_scythe",
	},
	beargerfur_sack =
	{
		"beargerfursack_mystical",
		"beargerfursack_rose",
	},
	beargervest =
	{
		"beargervest_rose",
		"beargervest_yule",
	},
	bedroll_furry =
	{
		"bedroll_furry_bearger",
		"bedroll_furry_catcoon",
		"bedroll_furry_potato",
		"bedroll_furry_quilt_blue_frost",
		"bedroll_furry_quilt_green_hunters",
		"bedroll_furry_quilt_grey",
		"bedroll_furry_quilt_orange_honey",
		"bedroll_furry_quilt_red_polkadot",
		"bedroll_furry_quilt_red_redbird",
		"bedroll_furry_quilt_white_ivory",
		"bedroll_furry_spider",
	},
	beebox =
	{
		"beebox_crystal",
		"beebox_garden",
		"beebox_house",
		"beebox_victorian",
	},
	beebox_hermit =
	{
		"beebox_hermit_shiny",
		"beebox_hermit_yule",
	},
	beef_bell =
	{
		"cowbell_round",
	},
	beefalohat =
	{
		"beefalohat_fantasy",
		"beefalohat_klaus",
		"beefalohat_mystical",
		"beefalohat_pigking",
		"beefalohat_pigking_alt",
	},
	beehat =
	{
		"beehat_garden",
		"beehat_mourning",
		"beehat_sunhat",
	},
	beemine =
	{
		"beemine_heart",
		"beemine_jamjar",
	},
	bernie_active =
	{
		"bernie_cat_active",
		"bernie_dog_active",
	},
	bernie_big =
	{
		"bernie_cat_big",
		"bernie_cat_lunar_build",
		"bernie_cat_shadow_build",
		"bernie_dog_big",
		"bernie_dog_lunar_build",
		"bernie_dog_shadow_build",
	},
	bernie_inactive =
	{
		"bernie_cat",
		"bernie_dog",
	},
	berrybush =
	{
		"berrybush_cawnival",
		"berrybush_mystical",
		"berrybush_swamp",
	},
	berrybush_waxed =
	{
		"berrybush_waxed_cawnival",
		"berrybush_waxed_mystical",
		"berrybush_waxed_swamp",
	},
	birdcage =
	{
		"birdcage_adventure",
		"birdcage_circus",
		"birdcage_curly",
		"birdcage_gothic",
		"birdcage_gothicp",
		"birdcage_ornamental",
		"birdcage_pirate",
		"birdcage_romantic",
	},
	birdtrap =
	{
		"birdtrap_an",
	},
	blueamulet =
	{
		"amulet_blue_relic",
	},
	boat =
	{
		"boat_nautical",
		"boat_pirate_skin",
		"boat_tesla",
		"boat_wagstaff",
	},
	boat_grass =
	{
		"boat_grass_pirate",
	},
	boat_grass_item =
	{
		"boat_grass_pirate_item",
	},
	boat_item =
	{
		"boat_nautical_item",
		"boat_pirate_skin_item",
		"boat_tesla_item",
		"boat_wagstaff_item",
	},
	book_brimstone =
	{
		"book_brimstone_gilded",
	},
	book_research_station =
	{
		"book_research_station_howto",
	},
	book_silviculture =
	{
		"book_silviculture_livinglog",
	},
	book_sleep =
	{
		"book_sleep_magazine",
	},
	book_temperature =
	{
		"book_temperature_romance",
	},
	book_web =
	{
		"book_web_tallbird",
	},
	bookstation =
	{
		"bookstation_house",
	},
	boomerang =
	{
		"boomerang_bananarang",
		"boomerang_bandedwood",
		"boomerang_tiger",
	},
	bugnet =
	{
		"bugnet_frog",
		"bugnet_garden",
		"bugnet_lavaproof",
		"bugnet_spider",
		"bugnet_spider_white",
	},
	bundle =
	{
		"bundle_cawnival",
		"bundle_gothic",
		"bundle_kitchen",
		"bundle_metal",
		"bundle_mystical",
		"bundle_vintage",
	},
	bundlewrap =
	{
		"bundlewrap_cawnival",
		"bundlewrap_gothic",
		"bundlewrap_kitchen",
		"bundlewrap_metal",
		"bundlewrap_mystical",
		"bundlewrap_vintage",
	},
	bushhat =
	{
		"bushhat_cawnival",
		"bushhat_mystical",
		"bushhat_swamp",
	},
	campfire =
	{
		"campfire_cabin",
	},
	cane =
	{
		"cane_ancient",
		"cane_candycane",
		"cane_harlequin",
		"cane_rose",
		"cane_sharp",
		"cane_victorian",
	},
	catcoonhat =
	{
		"catcoonhat_clown",
		"catcoonhat_trapper_rooster",
		"catcoonhat_trapperup_rooster",
		"hat_puppy_cap",
	},
	cave_entrance =
	{
		"cave_entrance_fantasy",
		"cave_entrance_gothic",
	},
	cave_entrance_open =
	{
		"cave_entrance_open_fantasy",
		"cave_entrance_open_gothic",
	},
	cave_exit =
	{
		"cave_exit_fantasy",
		"cave_exit_gothic",
	},
	cavein_boulder =
	{
		"cavein_boulder_kettlebell",
	},
	chester =
	{
		"chester_horn",
		"chester_lamb",
		"chester_mystical",
		"chester_walrus",
	},
	chester_eyebone =
	{
		"chester_eyebone_horn",
		"chester_eyebone_lamb",
		"chester_eyebone_mystical",
		"chester_eyebone_walrus",
	},
	coldfirepit =
	{
		"coldfirepit_an",
		"coldfirepit_flower",
		"coldfirepit_gothic",
		"coldfirepit_teeth",
	},
	cookpot =
	{
		"cookpot_candy",
		"cookpot_cauldron",
		"cookpot_cauldronp",
		"cookpot_clay",
		"cookpot_kitchen",
		"cookpot_planet",
		"cookpot_survival",
		"cookpot_tureen",
	},
	critter_dragonling =
	{
		"dragonling_bat",
		"dragonling_batp",
		"dragonling_mantis",
		"dragonling_winter",
		"dragonling_wyvern",
	},
	critter_dragonling_builder =
	{
		"dragonling_bat_builder",
		"dragonling_batp_builder",
		"dragonling_mantis_builder",
		"dragonling_winter_builder",
		"dragonling_wyvern_builder",
	},
	critter_glomling =
	{
		"glomling_beardeddragon",
		"glomling_puft",
		"glomling_winter",
	},
	critter_glomling_builder =
	{
		"glomling_beardeddragon_builder",
		"glomling_puft_builder",
		"glomling_winter_builder",
	},
	critter_kitten =
	{
		"kitten_black",
		"kitten_winter",
	},
	critter_kitten_builder =
	{
		"kitten_black_builder",
		"kitten_winter_builder",
	},
	critter_lamb =
	{
		"lamb_cotl",
		"lamb_dark",
		"lamb_winter",
	},
	critter_lamb_builder =
	{
		"lamb_cotl_builder",
		"lamb_dark_builder",
		"lamb_winter_builder",
	},
	critter_lunarmothling =
	{
		"lunarmoth_bright",
	},
	critter_lunarmothling_builder =
	{
		"lunarmoth_bright_builder",
	},
	critter_perdling =
	{
		"perdling_crow",
		"perdling_pelican",
		"perdling_pollyrogers",
		"perdling_puffin",
		"perdling_rooster",
		"perdling_winter",
	},
	critter_perdling_builder =
	{
		"perdling_crow_builder",
		"perdling_pelican_builder",
		"perdling_pollyrogers_builder",
		"perdling_puffin_builder",
		"perdling_rooster_builder",
		"perdling_winter_builder",
	},
	critter_puppy =
	{
		"puppy_chow",
		"puppy_tzu",
		"puppy_winter",
	},
	critter_puppy_builder =
	{
		"puppy_chow_builder",
		"puppy_tzu_builder",
		"puppy_winter_builder",
	},
	critterlab =
	{
		"critterlab_fantasy",
		"critterlab_gothic",
	},
	decor_centerpiece =
	{
		"decor_centerpiece_cawnival",
		"decor_centerpiece_fantasy",
		"decor_centerpiece_hallowed",
		"decor_centerpiece_handmade",
		"decor_centerpiece_western",
	},
	decor_flowervase =
	{
		"decor_flowervase_cawnival",
		"decor_flowervase_fantasy",
		"decor_flowervase_hallowed",
		"decor_flowervase_handmade",
		"decor_flowervase_western",
	},
	decor_lamp =
	{
		"decor_lamp_cawnival",
		"decor_lamp_fantasy",
		"decor_lamp_hallowed",
		"decor_lamp_handmade",
		"decor_lamp_western",
	},
	decor_pictureframe =
	{
		"decor_pictureframe_cawnival",
		"decor_pictureframe_fantasy",
		"decor_pictureframe_hallowed",
		"decor_pictureframe_handmade",
		"decor_pictureframe_western",
	},
	decor_portraitframe =
	{
		"decor_portraitframe_cawnival",
		"decor_portraitframe_fantasy",
		"decor_portraitframe_hallowed",
		"decor_portraitframe_handmade",
		"decor_portraitframe_western",
	},
	deserthat =
	{
		"deserthat_fedora",
	},
	dock_woodposts =
	{
		"dock_woodposts_carved",
		"dock_woodposts_carved2",
		"dock_woodposts_carved3",
		"dock_woodposts_decorated",
		"dock_woodposts_decorated2",
		"dock_woodposts_decorated3",
		"dock_woodposts_kitchen",
		"dock_woodposts_kitchen2",
		"dock_woodposts_kitchen3",
	},
	dock_woodposts_item =
	{
		"dock_woodposts_carved2_item",
		"dock_woodposts_carved3_item",
		"dock_woodposts_carved_item",
		"dock_woodposts_decorated2_item",
		"dock_woodposts_decorated3_item",
		"dock_woodposts_decorated_item",
		"dock_woodposts_kitchen2_item",
		"dock_woodposts_kitchen3_item",
		"dock_woodposts_kitchen_item",
	},
	dragonflychest =
	{
		"dragonflychest_fantasy",
		"dragonflychest_kraken",
		"dragonflychest_upgraded_fantasy",
		"dragonflychest_upgraded_kraken",
	},
	dragonflyfurnace =
	{
		"dragonflyfurnace_adventure",
		"dragonflyfurnace_antique",
		"dragonflyfurnace_crystal",
	},
	dreadstonehat =
	{
		"hat_dreadstone_horn",
	},
	dug_berrybush =
	{
		"dug_berrybush_cawnival",
		"dug_berrybush_mystical",
		"dug_berrybush_swamp",
	},
	dug_berrybush_waxed =
	{
		"dug_berrybush_waxed_cawnival",
		"dug_berrybush_waxed_mystical",
		"dug_berrybush_waxed_swamp",
	},
	dug_gravestone =
	{
		"dug_gravestone_fantasy",
		"dug_gravestone_fantasy2",
		"dug_gravestone_fantasy3",
		"dug_gravestone_fantasy4",
		"dug_gravestone_gothic",
		"dug_gravestone_gothic2",
		"dug_gravestone_gothic3",
		"dug_gravestone_gothic4",
	},
	earmuffshat =
	{
		"earmuffshat_beeguard",
		"earmuffshat_deerclops",
	},
	endtable =
	{
		"endtable_carpet",
		"endtable_cawnival",
		"endtable_cawnival_alt",
		"endtable_dragonfly",
		"endtable_vintage",
	},
	eyebrellahat =
	{
		"eyebrellahat_adventure",
		"eyebrellahat_crystal",
		"eyebrellahat_fantasy",
		"eyebrellahat_rose",
		"eyebrellahat_victorian",
	},
	eyeturret =
	{
		"eyeturret_an",
	},
	eyeturret_item =
	{
		"eyeturret_anitem",
	},
	farm_hoe =
	{
		"farm_hoe_invisible",
		"farm_hoe_rustic",
	},
	featherfan =
	{
		"featherfan_exotic",
	},
	featherhat =
	{
		"featherhat_circus",
		"featherhat_exotic",
		"featherhat_victorian",
	},
	fence =
	{
		"fence_ancient",
		"fence_factory",
		"fence_fantasy",
		"fence_gingerbread",
		"fence_gothic",
		"fence_picketbrown",
		"fence_pickettan",
		"fence_picketwhite",
		"fence_shell",
		"fence_victorianblack",
		"fence_victorianbrass",
		"fence_victorianbronze",
	},
	fence_gate =
	{
		"fence_gate_ancient",
		"fence_gate_gingerbread",
		"fence_gate_gothic",
		"fence_gate_picketbrown",
		"fence_gate_pickettan",
		"fence_gate_picketwhite",
		"fence_gate_shell",
		"fence_gate_victorianblack",
		"fence_gate_victorianbrass",
		"fence_gate_victorianbronze",
	},
	fence_gate_item =
	{
		"fencegate_ancient_item",
		"fencegate_gingerbread_item",
		"fencegate_gothic_item",
		"fencegate_picketbrown_item",
		"fencegate_pickettan_item",
		"fencegate_picketwhite_item",
		"fencegate_shell_item",
		"fencegate_victorianblack_item",
		"fencegate_victorianbrass_item",
		"fencegate_victorianbronze_item",
	},
	fence_item =
	{
		"fence_ancient_item",
		"fence_factory_item",
		"fence_fantasy_item",
		"fence_gingerbread_item",
		"fence_gothic_item",
		"fence_picketbrown_item",
		"fence_pickettan_item",
		"fence_picketwhite_item",
		"fence_shell_item",
		"fence_victorianblack_item",
		"fence_victorianbrass_item",
		"fence_victorianbronze_item",
	},
	firepit =
	{
		"firepit_fanged",
		"firepit_fangedp",
		"firepit_firebird",
		"firepit_hole",
		"firepit_hole_alt",
		"firepit_kiln",
		"firepit_kiln_alt",
		"firepit_lava",
		"firepit_stonehenge",
		"firepit_victorian",
	},
	firestaff =
	{
		"firestaff_bee",
		"firestaff_flamelash",
		"firestaff_gungnir",
		"firestaff_hockey",
		"firestaff_lance",
		"firestaff_meteor",
		"firestaff_northern",
		"firestaff_rose",
	},
	firesuppressor =
	{
		"firesuppressor_circus",
		"firesuppressor_robot",
	},
	fish_box =
	{
		"fishbox_nautical",
		"fishbox_pirate",
	},
	fishingrod =
	{
		"fishingrod_block",
		"fishingrod_curl",
		"fishingrod_sword",
	},
	flotationcushion =
	{
		"flotationcushion_cawnival",
	},
	flowerhat =
	{
		"flowerhat_crown",
		"flowerhat_healing",
		"flowerhat_holly_wreath",
		"flowerhat_ribbon_wreath",
		"flowerhat_wreath",
	},
	footballhat =
	{
		"footballhat_adventure",
		"footballhat_combathelm",
		"footballhat_combathelm2",
		"footballhat_hockey",
		"footballhat_western",
		"hat_dog_helm",
	},
	gemsocket =
	{
		"gemsocket_crystal",
		"gemsocket_hallowpylon",
		"gemsocket_mystical",
	},
	glasscutter =
	{
		"glasscutter_mystical",
		"glasscutter_terraprisma",
	},
	glommer =
	{
		"glommer_fantasy",
	},
	glommerflower =
	{
		"glommerflower_fantasy",
	},
	goggleshat =
	{
		"goggleshat_fedora",
	},
	golden_farm_hoe =
	{
		"golden_farmhoe_garden",
		"golden_farmhoe_invisible",
	},
	goldenaxe =
	{
		"goldenaxe_invisible",
		"goldenaxe_northern",
	},
	goldenpickaxe =
	{
		"goldenpickaxe_invisible",
		"goldenpickaxe_northern",
	},
	goldenpitchfork =
	{
		"goldenpitchfork_invisible",
	},
	goldenshovel =
	{
		"goldenshovel_invisible",
		"goldenshovel_northern",
	},
	grass_umbrella =
	{
		"parasol_spring",
	},
	gravestone =
	{
		"gravestone_fantasy",
		"gravestone_fantasy2",
		"gravestone_fantasy3",
		"gravestone_fantasy4",
		"gravestone_gothic",
		"gravestone_gothic2",
		"gravestone_gothic3",
		"gravestone_gothic4",
	},
	greenamulet =
	{
		"amulet_green_relic",
	},
	greenstaff =
	{
		"greenstaff_an",
		"greenstaff_clockwork",
		"greenstaff_planet",
	},
	hambat =
	{
		"hambat_nautical",
		"hambat_potroast",
		"hambat_spiralcut",
	},
	hammer =
	{
		"hammer_crowbar",
		"hammer_forge",
		"hammer_hammush",
		"hammer_invisible",
	},
	hawaiianshirt =
	{
		"torso_hawaiian_blue",
		"torso_hawaiian_eyeplant",
		"torso_hawaiian_palmtree1",
		"torso_hawaiian_palmtree2",
		"torso_hawaiian_red",
	},
	heatrock =
	{
		"heatrock_fantasy",
		"heatrock_fire",
		"heatrock_planet",
	},
	hermit_chair_rocking =
	{
		"hermit_chair_rocking_yule",
	},
	hermitcrab =
	{
		"hermitcrab_coral",
		"hermitcrab_hairy",
		"hermitcrab_none",
		"hermitcrab_peacock",
		"hermitcrab_pointy",
	},
	hermitcrab_lightpost =
	{
		"hermitcrab_lightpost_yule",
	},
	hermitcrab_teashop =
	{
		"hermitcrab_teashop_yule",
	},
	hermithotspring =
	{
		"hermithotspring_yule",
	},
	hermithotspring_constr =
	{
		"hermithotspring_constr_yule",
	},
	hermithouse =
	{
		"hermithouse_yule",
	},
	hermithouse2 =
	{
		"hermithouse2_yule",
	},
	hermithouse_construction1 =
	{
		"hermithouse_construction1_yule",
	},
	hermithouse_construction2 =
	{
		"hermithouse_construction2_yule",
	},
	hermithouse_construction3 =
	{
		"hermithouse_construction3_yule",
	},
	hermithouse_ornament =
	{
		"hermithouse_ornament_bow",
		"hermithouse_ornament_coral",
		"hermithouse_ornament_driftwood",
		"hermithouse_ornament_mushroom",
		"hermithouse_ornament_saltcrystal",
		"hermithouse_ornament_sanddollar",
		"hermithouse_ornament_snowflake",
		"hermithouse_ornament_stocking",
		"hermithouse_ornament_wood",
		"hermithouse_ornament_wreath",
	},
	hivehat =
	{
		"hivehat_an",
		"hivehat_cawnival",
		"hivehat_joker",
	},
	hutch =
	{
		"hutch_fantasy",
		"hutch_swamp",
	},
	hutch_fishbowl =
	{
		"hutch_fishbowl_fantasy",
		"hutch_fishbowl_swamp",
	},
	icebox =
	{
		"icebox_coffin",
		"icebox_crystal",
		"icebox_kitchen",
		"icebox_porcelain",
		"icebox_victorian",
	},
	icehat =
	{
		"hat_ice_shark",
	},
	icepack =
	{
		"icepack_kitchen",
	},
	icestaff =
	{
		"icestaff_bee",
		"icestaff_gungnir",
		"icestaff_hockey",
		"icestaff_icerod",
		"icestaff_lance",
		"icestaff_northern",
		"icestaff_rose",
	},
	insanityrock =
	{
		"insanityrock_fantasy",
		"insanityrock_gothic",
	},
	krampus_sack =
	{
		"krampus_sack_basket",
		"krampus_sack_garden",
		"krampus_sack_voidbag",
	},
	lantern =
	{
		"lantern_crystal",
		"lantern_flower",
		"lantern_flower_alt",
		"lantern_gothic",
		"lantern_insect",
		"lantern_mummy",
		"lantern_mummy_alt",
		"lantern_mystical",
		"lantern_retro",
		"lantern_tesla",
		"lantern_winter",
		"lantern_winter_alt",
	},
	lighter =
	{
		"lighter_glass",
		"lighter_haunteddoll",
		"lighter_heart",
		"lighter_old",
		"lighter_ragged",
		"lighter_rose",
	},
	lightning_rod =
	{
		"lightning_rod_adventure",
		"lightning_rod_gothic",
		"lightning_rod_nautical",
		"lightning_rod_retro",
		"lightning_rod_robot",
	},
	lucy =
	{
		"lucy_broadaxe",
		"lucy_chained",
		"lucy_picnic",
		"lucy_punk",
	},
	lunarplanthat =
	{
		"lunarplanthat_brave",
		"lunarplanthat_knight",
	},
	lureplant =
	{
		"eyeplant_trap_plantera",
	},
	lureplantbulb =
	{
		"eyeplant_bulb_trap_plantera",
	},
	magician_chest =
	{
		"magician_chest_shadow",
	},
	mast =
	{
		"mast_crabking",
		"mast_crabking_alt",
		"mast_nautical",
		"mast_pirate",
		"mast_rose",
		"mast_rose_alt",
	},
	mast_item =
	{
		"mast_crabking_alt_item",
		"mast_crabking_item",
		"mast_nautical_item",
		"mast_pirate_item",
		"mast_rose_alt_item",
		"mast_rose_item",
	},
	mast_malbatross =
	{
		"mast_malbatross_tesla",
		"mast_malbatross_wagstaff",
	},
	mast_malbatross_item =
	{
		"mast_malbatross_tesla_item",
		"mast_malbatross_wagstaff_item",
	},
	mastupgrade_lamp =
	{
		"mastupgradelamp_nautical",
	},
	mastupgrade_lamp_item =
	{
		"mastupgradelamp_item_nautical",
	},
	mastupgrade_lightningrod =
	{
		"mastupgrade_lightningrod_nautical",
	},
	mastupgrade_lightningrod_item =
	{
		"mastupgrade_lightningrod_item_nautical",
	},
	mastupgrade_lightningrod_top =
	{
		"mastupgrade_lightningrod_nautical_top",
	},
	meatrack =
	{
		"meatrack_ancient",
		"meatrack_butcher",
		"meatrack_circus",
		"meatrack_victorian",
	},
	meatrack_hermit =
	{
		"meatrack_hermit_coral",
		"meatrack_hermit_yule",
	},
	meatrack_hermit_multi =
	{
		"meatrack_hermit_multi_coral",
		"meatrack_hermit_multi_yule",
	},
	mermhat =
	{
		"mermhat_clown",
	},
	mermhouse_crafted =
	{
		"mermhouse_crafted_fantasy",
		"mermhouse_crafted_mystical",
		"mermhouse_crafted_swamp",
	},
	mermwatchtower =
	{
		"mermwatchtower_mystical",
		"mermwatchtower_swamp",
	},
	mighty_gym =
	{
		"mighty_gym_ancient",
	},
	minerhat =
	{
		"minerhat_bonnet",
		"minerhat_cowboy",
		"minerhat_floppy",
		"minerhat_western",
	},
	minisign =
	{
		"minisign_fantasy",
		"minisign_ornate",
		"minisign_picketbrown",
		"minisign_pickettan",
		"minisign_picketwhite",
	},
	minisign_drawn =
	{
		"minisign_fantasy_drawn",
		"minisign_ornate_drawn",
		"minisign_picketbrown_drawn",
		"minisign_pickettan_drawn",
		"minisign_picketwhite_drawn",
	},
	minisign_item =
	{
		"minisign_fantasy_item",
		"minisign_ornate_item",
		"minisign_picketbrown_item",
		"minisign_pickettan_item",
		"minisign_picketwhite_item",
	},
	molehat =
	{
		"molehat_goggles",
		"molehat_tail",
	},
	monkey_mediumhat =
	{
		"monkeyhatmedium_blue",
		"monkeyhatmedium_red",
	},
	monkey_smallhat =
	{
		"monkeyhatsmall_beads",
		"monkeyhatsmall_belt",
	},
	moondial =
	{
		"moondial_an",
	},
	multitool_axe_pickaxe =
	{
		"multitool_axe_pickaxe_pickaxeaxe",
	},
	mushroom_farm =
	{
		"mushroom_farm_handmade",
		"mushroom_farm_mystical",
	},
	mushroom_light =
	{
		"mushroom_light_an",
		"mushroom_light_festive",
		"mushroom_light_hallowed",
		"mushroom_light_tiffany",
	},
	mushroom_light2 =
	{
		"mushroom_light2_an",
		"mushroom_light2_cawnival",
		"mushroom_light2_hallowed",
		"mushroom_light2_lily",
		"mushroom_light2_victorian",
	},
	nightlight =
	{
		"nightmare_torch_relic",
	},
	nightstick =
	{
		"nightstick_swamp",
	},
	nightsword =
	{
		"nightsword_cotl",
		"nightsword_curve",
		"nightsword_lightsbane",
		"nightsword_sharp",
		"nightsword_wizard",
	},
	oar =
	{
		"oar_invisible",
		"oar_swamp",
	},
	oar_driftwood =
	{
		"oar_driftwood_invisible",
		"oar_driftwood_swamp",
	},
	ocean_trawler =
	{
		"ocean_trawler_pirate",
	},
	ocean_trawler_kit =
	{
		"ocean_trawler_pirate_kit",
	},
	oceanfishingrod =
	{
		"oceanfishingrod_hotline",
		"oceanfishingrod_ice",
		"oceanfishingrod_ice_alt",
		"oceanfishingrod_nautical",
	},
	opalstaff =
	{
		"moonstaff_crystal",
		"moonstaff_portal",
		"moonstaff_relic",
		"moonstaff_swamp",
	},
	orangeamulet =
	{
		"amulet_orange_planet",
		"amulet_orange_relic",
	},
	orangestaff =
	{
		"orangestaff_ancient",
		"orangestaff_candycane",
		"orangestaff_harlequin",
		"orangestaff_rodofdiscord",
		"orangestaff_rose",
		"orangestaff_sharp",
		"orangestaff_victorian",
	},
	panflute =
	{
		"panflute_an",
		"panflute_harlequin",
		"panflute_swamp",
	},
	phonograph =
	{
		"decor_phonograph_cawnival",
		"decor_phonograph_fantasy",
		"decor_phonograph_hallowed",
		"decor_phonograph_handmade",
		"decor_phonograph_western",
	},
	pickaxe =
	{
		"pickaxe_feathered",
		"pickaxe_invisible",
		"pickaxe_northern",
		"pickaxe_reavershark",
		"pickaxe_scythe",
		"pickaxe_scythe_alt",
		"pickaxe_victorian",
	},
	piggyback =
	{
		"piggyback_elephant",
		"piggyback_nose",
	},
	pighouse =
	{
		"pighouse_cabin",
		"pighouse_gothic",
		"pighouse_logcabin",
	},
	pitchfork =
	{
		"pitchfork_invisible",
	},
	portableblender =
	{
		"portable_blender_porcelain",
		"portable_blender_rustic",
		"portable_blender_silver",
		"portable_blender_survivor",
	},
	portableblender_item =
	{
		"portable_blender_porcelain_item",
		"portable_blender_rustic_item",
		"portable_blender_silver_item",
		"portable_blender_survivor_item",
	},
	portablecookpot =
	{
		"portable_cook_pot_porcelain",
		"portable_cook_pot_rustic",
		"portable_cook_pot_silver",
		"portable_cook_pot_survivor",
	},
	portablecookpot_item =
	{
		"portable_cook_pot_porcelain_item",
		"portable_cook_pot_rustic_item",
		"portable_cook_pot_silver_item",
		"portable_cook_pot_survivor_item",
	},
	portablespicer =
	{
		"portable_spicer_porcelain",
		"portable_spicer_rustic",
		"portable_spicer_silver",
		"portable_spicer_survivor",
	},
	portablespicer_item =
	{
		"portable_spicer_porcelain_item",
		"portable_spicer_rustic_item",
		"portable_spicer_silver_item",
		"portable_spicer_survivor_item",
	},
	pottedfern =
	{
		"pottedfern_cotl",
		"pottedfern_cotl2",
		"pottedfern_cotl3",
		"pottedfern_rose",
		"pottedfern_rose2",
		"pottedfern_rose3",
	},
	premiumwateringcan =
	{
		"premiumwateringcan_koalefant",
	},
	pumpkinhat =
	{
		"pumpkinhat_2",
		"pumpkinhat_3",
	},
	purpleamulet =
	{
		"amulet_purple_relic",
	},
	rabbithouse =
	{
		"rabbithouse_carrat",
		"rabbithouse_hallowed",
		"rabbithouse_yule",
	},
	raincoat =
	{
		"raincoat_poncho",
		"raincoat_western",
	},
	rainhat =
	{
		"rainhat_bonnet",
		"rainhat_cowboy",
		"rainhat_floppy",
		"rainhat_western",
	},
	rainometer =
	{
		"rainometer_circus",
		"rainometer_swamp",
	},
	razor =
	{
		"razor_barber",
		"razor_scissors",
		"razor_straight",
	},
	record =
	{
		"record_creepyforest",
		"record_drstyle",
		"record_efs",
		"record_hallowednights",
	},
	reflectivevest =
	{
		"reflectivevest_cawnival",
	},
	researchlab =
	{
		"researchlab_gothic",
		"researchlab_green",
		"researchlab_party",
		"researchlab_retro",
	},
	researchlab2 =
	{
		"researchlab2_alchemytable",
		"researchlab2_crystal",
		"researchlab2_gothic",
		"researchlab2_pod",
		"researchlab2_science",
	},
	researchlab3 =
	{
		"researchlab3_adventure",
		"researchlab3_ancient",
		"researchlab3_crystal",
		"researchlab3_monster",
		"researchlab3_nature",
	},
	researchlab4 =
	{
		"researchlab4_catcoon_costume",
		"researchlab4_catcoon_costumep",
		"researchlab4_chef",
		"researchlab4_chester_costume",
		"researchlab4_chester_costumep",
		"researchlab4_derby",
		"researchlab4_festive_bell_red_firehound",
		"researchlab4_fish",
		"researchlab4_glommer_costume",
		"researchlab4_glommer_costumep",
		"researchlab4_hutch_costume",
		"researchlab4_hutch_costumep",
		"researchlab4_merchant",
		"researchlab4_tophat_circus",
		"researchlab4_tophat_harlequin",
		"researchlab4_tophat_spiked",
		"researchlab4_tophat_wizard",
		"researchlab4_western",
		"researchlab4_witch_pyre",
	},
	reskin_tool =
	{
		"reskin_tool_bouquet",
		"reskin_tool_brush",
		"reskin_tool_toilet",
		"reskin_tool_wand",
	},
	resurrectionstatue =
	{
		"resurrectionstatue_barber",
		"resurrectionstatue_monster",
	},
	resurrectionstone =
	{
		"resurrectionstone_fantasy",
		"resurrectionstone_gothic",
	},
	reviver =
	{
		"reviver_cupid",
		"reviver_cupid_2",
		"reviver_cupid_2alt",
		"reviver_cupid_3",
		"reviver_cupid_3alt",
		"reviver_cupid_4",
		"reviver_cupid_4alt",
		"reviver_cupid_alt",
		"reviver_lifecrystal",
	},
	ruins_bat =
	{
		"ruins_bat_an",
		"ruins_bat_arcane",
		"ruins_bat_heavy",
	},
	ruinshat =
	{
		"ruinshat_an",
		"ruinshat_arcane",
	},
	ruinsrelic_chair =
	{
		"ruinsrelic_chair_tesla",
		"ruinsrelic_chair_toilet",
	},
	saddle_basic =
	{
		"saddle_basic_western",
		"saddle_basic_yotb",
		"saddle_basic_yotbalt",
	},
	saltbox =
	{
		"saltbox_kitchen",
		"saltbox_nautical",
		"saltbox_shaker",
		"saltbox_victorian",
	},
	sanityrock =
	{
		"sanityrock_fantasy",
		"sanityrock_gothic",
	},
	sculptingtable =
	{
		"sculptingtable_gothic",
		"sculptingtable_swamp",
	},
	seafaring_prototyper =
	{
		"seafaring_prototyper_lighthouse",
	},
	seedpouch =
	{
		"seedpouch_garden",
		"seedpouch_rustic",
	},
	sewing_mannequin =
	{
		"sewing_mannequin_an",
	},
	shovel =
	{
		"shovel_feathered",
		"shovel_heart",
		"shovel_invisible",
		"shovel_northern",
		"shovel_victorian",
	},
	siestahut =
	{
		"siestahut_cawnival",
		"siestahut_mystical",
		"siestahut_swamp",
	},
	sisturn =
	{
		"sisturn_beachhouse",
		"sisturn_nest",
		"sisturn_victorian",
	},
	skeletonhat =
	{
		"skeletonhat_mythical",
		"skeletonhat_relic",
		"skeletonhat_shadowhelmet",
	},
	slingshot =
	{
		"slingshot_bandaged",
		"slingshot_nature",
		"slingshot_spiked",
		"slingshot_straws",
	},
	slingshot2 =
	{
		"slingshot2_bandaged",
		"slingshot2_nature",
		"slingshot2_spiked",
		"slingshot2_straws",
	},
	slingshot2ex =
	{
		"slingshot2ex_bandaged",
		"slingshot2ex_nature",
		"slingshot2ex_spiked",
		"slingshot2ex_straws",
	},
	slingshot999ex =
	{
		"slingshot999ex_bandaged",
		"slingshot999ex_nature",
		"slingshot999ex_spiked",
		"slingshot999ex_straws",
	},
	slingshotex =
	{
		"slingshotex_bandaged",
		"slingshotex_nature",
		"slingshotex_spiked",
		"slingshotex_straws",
	},
	spear =
	{
		"spear_bee",
		"spear_forge_gungnir",
		"spear_forge_lance",
		"spear_hockey",
		"spear_northern",
		"spear_ragged",
		"spear_rose",
		"spear_simple",
	},
	spear_wathgrithr =
	{
		"spear_wathgrithr_lunar",
		"spear_wathgrithr_northern",
		"spear_wathgrithr_valkyrie",
		"spear_wathgrithr_wrestle",
	},
	spear_wathgrithr_lightning =
	{
		"spear_wathgrithr_lightning_lunar",
		"spear_wathgrithr_lightning_northern",
		"spear_wathgrithr_lightning_valkyrie",
		"spear_wathgrithr_lightning_wrestle",
	},
	spear_wathgrithr_lightning_charged =
	{
		"spear_wathgrithr_lightning_charged_lunar",
		"spear_wathgrithr_lightning_charged_northern",
		"spear_wathgrithr_lightning_charged_valkyrie",
		"spear_wathgrithr_lightning_charged_wrestle",
	},
	spicepack =
	{
		"spicepack_porcelain",
		"spicepack_rustic",
		"spicepack_silver",
		"spicepack_survivor",
	},
	staff_tornado =
	{
		"tornado_stick_crow",
	},
	stagehand =
	{
		"stagehand_carpet",
		"stagehand_cawnival",
		"stagehand_cawnival_alt",
		"stagehand_dragonfly",
		"stagehand_vintage",
	},
	steeringwheel =
	{
		"steeringwheel_nautical",
		"steeringwheel_tesla",
		"steeringwheel_wagstaff",
	},
	steeringwheel_item =
	{
		"steeringwheel_nautical_item",
		"steeringwheel_tesla_item",
		"steeringwheel_wagstaff_item",
	},
	stone_chair =
	{
		"stone_chair_shell",
		"stone_chair_victorianblack",
		"stone_chair_victorianbrass",
		"stone_chair_victorianbronze",
	},
	stone_stool =
	{
		"stonechair_stool_shell",
		"stonechair_stool_victorianblack",
		"stonechair_stool_victorianbrass",
		"stonechair_stool_victorianbronze",
	},
	stone_table_round =
	{
		"stonetable_round_shell",
		"stonetable_round_victorianblack",
		"stonetable_round_victorianbrass",
		"stonetable_round_victorianbronze",
	},
	stone_table_square =
	{
		"stonetable_square_shell",
		"stonetable_square_victorianblack",
		"stonetable_square_victorianbrass",
		"stonetable_square_victorianbronze",
	},
	strawhat =
	{
		"strawhat_bonnet",
		"strawhat_cowboy",
		"strawhat_floppy",
		"strawhat_western",
	},
	succulent_potted =
	{
		"succulent_potted_bearclaw",
	},
	supertacklecontainer =
	{
		"supertacklecontainer_shell",
		"supertacklecontainer_shiny",
	},
	tacklecontainer =
	{
		"tacklecontainer_shell",
		"tacklecontainer_shiny",
	},
	tacklestation =
	{
		"tackle_station_shell",
	},
	telebase =
	{
		"telebase_crystal",
		"telebase_hallowpylon",
		"telebase_mystical",
	},
	telestaff =
	{
		"telestaff_crystal",
		"telestaff_mystical",
		"telestaff_shadowbeam",
	},
	tent =
	{
		"tent_an",
		"tent_ancient",
		"tent_beach",
		"tent_circus",
		"tent_kid",
		"tent_leaf",
		"tent_spider",
	},
	tophat =
	{
		"hat_catcoon_costume",
		"hat_catcoon_costumep",
		"hat_chester_costume",
		"hat_chester_costumep",
		"hat_glommer_costume",
		"hat_glommer_costumep",
		"hat_hutch_costume",
		"hat_hutch_costumep",
		"tophat_chef",
		"tophat_circus",
		"tophat_derby",
		"tophat_festive_bell_red_firehound",
		"tophat_fish",
		"tophat_harlequin",
		"tophat_merchant",
		"tophat_spiked",
		"tophat_western",
		"tophat_witch_pyre",
		"tophat_wizard",
	},
	torch =
	{
		"torch_barber",
		"torch_carrat",
		"torch_carrat_alt",
		"torch_nautical",
		"torch_pillar",
		"torch_pillar_alt",
		"torch_pronged",
		"torch_rag",
		"torch_shadow",
		"torch_shadow_alt",
		"torch_spooky",
		"torch_spookyp",
		"torch_tesla",
	},
	tornado =
	{
		"tornado_crow",
	},
	townportal =
	{
		"townportal_relic",
	},
	trap =
	{
		"trap_basket",
		"trap_metal",
	},
	trap_teeth =
	{
		"trap_teeth_rose",
		"trap_teeth_tiger",
	},
	treasurechest =
	{
		"treasurechest_ancient",
		"treasurechest_cake",
		"treasurechest_carpetbag",
		"treasurechest_clock",
		"treasurechest_corruption",
		"treasurechest_cotl_basic",
		"treasurechest_cotl_fancy",
		"treasurechest_crimson",
		"treasurechest_cupid",
		"treasurechest_cupidalt",
		"treasurechest_gingerbread",
		"treasurechest_monster",
		"treasurechest_posh",
		"treasurechest_poshprint",
		"treasurechest_sacred",
		"treasurechest_steamertrunk",
		"treasurechest_traincase",
		"treasurechest_traveltrunk",
		"treasurechest_upgraded_ancient",
		"treasurechest_upgraded_cake",
		"treasurechest_upgraded_carpetbag",
		"treasurechest_upgraded_clock",
		"treasurechest_upgraded_corruption",
		"treasurechest_upgraded_cotl_basic",
		"treasurechest_upgraded_cotl_fancy",
		"treasurechest_upgraded_crimson",
		"treasurechest_upgraded_cupid",
		"treasurechest_upgraded_gingerbread",
		"treasurechest_upgraded_monster",
		"treasurechest_upgraded_posh",
		"treasurechest_upgraded_poshprint",
		"treasurechest_upgraded_sacred",
		"treasurechest_upgraded_steamertrunk",
		"treasurechest_upgraded_traincase",
		"treasurechest_upgraded_traveltrunk",
		"treasurechest_upgraded_vintage",
		"treasurechest_vintage",
	},
	trident =
	{
		"trident_merm",
	},
	trophyscale_fish =
	{
		"trophyscale_fish_handmade",
	},
	trophyscale_oversizedveggies =
	{
		"trophyscale_oversizedveggies_plant",
	},
	trunkvest_summer =
	{
		"armor_trunkvest_summer_quilted",
	},
	trunkvest_winter =
	{
		"armor_trunkvest_winter_quilted",
	},
	umbrella =
	{
		"umbrella_circus",
		"umbrella_heart",
		"umbrella_parasol",
		"umbrella_spider",
	},
	wagdrone_rolling =
	{
		"wagdrone_rolling_fancy",
		"wagdrone_rolling_spikey",
	},
	walkingplank =
	{
		"walkingplank_nautical",
		"walkingplank_pirate_skin",
		"walkingplank_tesla",
		"walkingplank_wagstaff",
	},
	walkingplank_grass =
	{
		"walkingplank_grass_pirate",
	},
	wall_dreadstone =
	{
		"wall_dreadstone_relic",
	},
	wall_dreadstone_item =
	{
		"wall_dreadstone_relicitem",
	},
	wall_hay =
	{
		"wall_hay_corn",
	},
	wall_hay_item =
	{
		"wall_hay_cornitem",
	},
	wall_moonrock =
	{
		"wall_moonrock_victorian",
	},
	wall_moonrock_item =
	{
		"wall_moonrock_victorianitem",
	},
	wall_ruins =
	{
		"wall_ruins_thulecite",
		"wall_ruins_thulecite2",
		"wall_ruins_thulecite2_alt",
		"wall_ruins_thulecite_alt",
		"wall_ruins_victorian",
	},
	wall_ruins_item =
	{
		"wall_ruins_thulecite2item",
		"wall_ruins_thulecite2item_alt",
		"wall_ruins_thulecite_alt_item",
		"wall_ruins_thuleciteitem",
		"wall_ruins_victorianitem",
	},
	wall_stone =
	{
		"wall_stone_an",
		"wall_stone_ancient",
		"wall_stone_ancient_alt",
		"wall_stone_gothic",
		"wall_stone_shell",
		"wall_stone_victorian",
	},
	wall_stone_item =
	{
		"wall_stone_ancient_alt_item",
		"wall_stone_ancientitem",
		"wall_stone_anitem",
		"wall_stone_gothicitem",
		"wall_stone_shellitem",
		"wall_stone_victorianitem",
	},
	wall_wood =
	{
		"wall_wood_ornate",
	},
	wall_wood_item =
	{
		"wall_wood_ornateitem",
	},
	walrushat =
	{
		"walrushat_blue",
		"walrushat_cawnival",
		"walrushat_ceremonial",
		"walrushat_party",
	},
	walter =
	{
		"walter_ancient",
		"walter_bee",
		"walter_bee_d",
		"walter_bee_p",
		"walter_detective",
		"walter_formal",
		"walter_ice",
		"walter_lunar",
		"walter_nature",
		"walter_none",
		"walter_rose",
		"walter_shadow",
		"walter_survivor",
		"walter_ventriloquist",
		"walter_victorian",
		"walter_yule",
	},
	walterhat =
	{
		"walterhat_ancient",
		"walterhat_bee",
		"walterhat_beep",
		"walterhat_detective",
		"walterhat_formal",
		"walterhat_ice",
		"walterhat_lunar",
		"walterhat_nature",
		"walterhat_rose",
		"walterhat_shadow",
		"walterhat_survivor",
		"walterhat_ventriloquist",
		"walterhat_victorian",
		"walterhat_yule",
	},
	wanda =
	{
		"wanda_bishop",
		"wanda_bishop_d",
		"wanda_bishop_p",
		"wanda_formal",
		"wanda_ice",
		"wanda_lunar",
		"wanda_masquerade",
		"wanda_nature",
		"wanda_none",
		"wanda_rose",
		"wanda_shadow",
		"wanda_steampunk",
		"wanda_western",
		"wanda_yule",
	},
	wardrobe =
	{
		"wardrobe_armoire",
		"wardrobe_crystal",
		"wardrobe_gothic",
		"wardrobe_heart",
		"wardrobe_vine",
		"wardrobe_yule",
	},
	warly =
	{
		"warly_candyman",
		"warly_carrat",
		"warly_carrat_d",
		"warly_carrat_p",
		"warly_chef",
		"warly_fisherman",
		"warly_formal",
		"warly_ice",
		"warly_lunar",
		"warly_masquerade",
		"warly_nature",
		"warly_none",
		"warly_pirate",
		"warly_rose",
		"warly_shadow",
		"warly_survivor",
		"warly_victorian",
		"warly_yule",
	},
	wateringcan =
	{
		"wateringcan_cactus",
		"wateringcan_rustic",
	},
	watermelonhat =
	{
		"watermelonhat_banana",
		"watermelonhat_cantaloupe",
		"watermelonhat_pumpkin",
	},
	wathgrithr =
	{
		"wathgrithr_ancient",
		"wathgrithr_combatant",
		"wathgrithr_cook",
		"wathgrithr_deerclops",
		"wathgrithr_deerclops_d",
		"wathgrithr_deerclops_p",
		"wathgrithr_formal",
		"wathgrithr_formalp",
		"wathgrithr_gladiator",
		"wathgrithr_ice",
		"wathgrithr_lunar",
		"wathgrithr_magma",
		"wathgrithr_masquerade",
		"wathgrithr_nature",
		"wathgrithr_none",
		"wathgrithr_pirate",
		"wathgrithr_rose",
		"wathgrithr_rosep",
		"wathgrithr_scarecrow",
		"wathgrithr_shadow",
		"wathgrithr_shadowp",
		"wathgrithr_survivor",
		"wathgrithr_survivorp",
		"wathgrithr_valkyrie",
		"wathgrithr_victorian",
		"wathgrithr_western",
		"wathgrithr_wrestler",
		"wathgrithr_yule",
	},
	wathgrithr_improvedhat =
	{
		"wathgrithr_improvedhat_flower",
		"wathgrithr_improvedhat_lunar",
		"wathgrithr_improvedhat_valkyrie",
		"wathgrithr_improvedhat_western",
		"wathgrithr_improvedhat_wrestle",
	},
	wathgrithrhat =
	{
		"wathgrithrhat_flower",
		"wathgrithrhat_lunar",
		"wathgrithrhat_valkyrie",
		"wathgrithrhat_western",
		"wathgrithrhat_wrestle",
	},
	waxwell =
	{
		"waxwell_combatant",
		"waxwell_cook",
		"waxwell_formal",
		"waxwell_formalp",
		"waxwell_gladiator",
		"waxwell_ice",
		"waxwell_krampus",
		"waxwell_krampus_d",
		"waxwell_krampus_p",
		"waxwell_lunar",
		"waxwell_magma",
		"waxwell_masquerade",
		"waxwell_nature",
		"waxwell_none",
		"waxwell_pirate",
		"waxwell_rose",
		"waxwell_rosep",
		"waxwell_spring",
		"waxwell_survivor",
		"waxwell_survivorp",
		"waxwell_unshadow",
		"waxwell_unshadowp",
		"waxwell_vampire",
		"waxwell_victorian",
		"waxwell_wizard",
		"waxwell_yule",
	},
	webber =
	{
		"webber_bat",
		"webber_bat_d",
		"webber_bat_p",
		"webber_boy",
		"webber_combatant",
		"webber_cook",
		"webber_formal",
		"webber_formalp",
		"webber_gladiator",
		"webber_ice",
		"webber_lunar",
		"webber_magma",
		"webber_masquerade",
		"webber_nature",
		"webber_none",
		"webber_pirate",
		"webber_punk",
		"webber_rose",
		"webber_rosep",
		"webber_shadow",
		"webber_shadowp",
		"webber_spring",
		"webber_survivor",
		"webber_survivorp",
		"webber_victorian",
		"webber_wrestler",
		"webber_yule",
	},
	webber_beard =
	{
		"webber_beard_bat",
		"webber_beard_boy",
		"webber_beard_formal",
		"webber_beard_gladiator",
		"webber_beard_ice",
		"webber_beard_lunar",
		"webber_beard_magma",
		"webber_beard_masquerade",
		"webber_beard_nature",
		"webber_beard_pirate",
		"webber_beard_punk",
		"webber_beard_rose",
		"webber_beard_shadow",
		"webber_beard_spring",
		"webber_beard_survivor",
		"webber_beard_victorian",
		"webber_beard_wrestler",
		"webber_beard_yule",
	},
	wendy =
	{
		"wendy_ancient",
		"wendy_combatant",
		"wendy_cook",
		"wendy_creepy",
		"wendy_formal",
		"wendy_formalp",
		"wendy_gladiator",
		"wendy_handmedown",
		"wendy_ice",
		"wendy_lunar",
		"wendy_lureplant",
		"wendy_lureplant_d",
		"wendy_lureplant_p",
		"wendy_magma",
		"wendy_masquerade",
		"wendy_nature",
		"wendy_none",
		"wendy_pirate",
		"wendy_rose",
		"wendy_rosep",
		"wendy_shadow",
		"wendy_shadowp",
		"wendy_survivor",
		"wendy_survivorp",
		"wendy_victorian",
		"wendy_yule",
	},
	wes =
	{
		"wes_clown",
		"wes_combatant",
		"wes_cook",
		"wes_formal",
		"wes_formalp",
		"wes_gladiator",
		"wes_harlequin",
		"wes_ice",
		"wes_lunar",
		"wes_magma",
		"wes_mandrake",
		"wes_mandrake_d",
		"wes_mandrake_p",
		"wes_masquerade",
		"wes_nature",
		"wes_none",
		"wes_pirate",
		"wes_rose",
		"wes_rosep",
		"wes_shadow",
		"wes_shadowp",
		"wes_survivor",
		"wes_survivorp",
		"wes_victorian",
		"wes_western",
		"wes_wrestler",
		"wes_yule",
	},
	whip =
	{
		"whip_snapthorn",
	},
	wickerbottom =
	{
		"wickerbottom_combatant",
		"wickerbottom_cook",
		"wickerbottom_formal",
		"wickerbottom_formalp",
		"wickerbottom_gladiator",
		"wickerbottom_ice",
		"wickerbottom_lightninggoat",
		"wickerbottom_lightninggoat_d",
		"wickerbottom_lightninggoat_p",
		"wickerbottom_lunar",
		"wickerbottom_magma",
		"wickerbottom_masquerade",
		"wickerbottom_nature",
		"wickerbottom_none",
		"wickerbottom_ornate",
		"wickerbottom_pirate",
		"wickerbottom_rose",
		"wickerbottom_rosep",
		"wickerbottom_shadow",
		"wickerbottom_shadowp",
		"wickerbottom_spiderwitch",
		"wickerbottom_survivor",
		"wickerbottom_survivorp",
		"wickerbottom_victorian",
		"wickerbottom_yule",
	},
	willow =
	{
		"willow_ancient",
		"willow_combatant",
		"willow_cook",
		"willow_dowdy",
		"willow_dragonfly",
		"willow_dragonfly_d",
		"willow_dragonfly_p",
		"willow_formal",
		"willow_formalp",
		"willow_gladiator",
		"willow_haunteddoll",
		"willow_ice",
		"willow_lunar",
		"willow_magma",
		"willow_masquerade",
		"willow_nature",
		"willow_none",
		"willow_pirate",
		"willow_rose",
		"willow_rosep",
		"willow_shadow",
		"willow_shadowp",
		"willow_spring",
		"willow_survivor",
		"willow_survivorp",
		"willow_victorian",
		"willow_yule",
	},
	wilson =
	{
		"wilson_barber",
		"wilson_combatant",
		"wilson_cook",
		"wilson_formal",
		"wilson_formalp",
		"wilson_gladiator",
		"wilson_ice",
		"wilson_lunar",
		"wilson_madscience",
		"wilson_magma",
		"wilson_masquerade",
		"wilson_nature",
		"wilson_none",
		"wilson_pigguard",
		"wilson_pigguard_d",
		"wilson_pigguard_p",
		"wilson_pirate",
		"wilson_rose",
		"wilson_rosep",
		"wilson_shadow",
		"wilson_shadowp",
		"wilson_spring",
		"wilson_survivor",
		"wilson_survivorp",
		"wilson_victorian",
		"wilson_yule",
	},
	wilson_beard =
	{
		"wilson_beard_barber",
		"wilson_beard_formal",
		"wilson_beard_gladiator",
		"wilson_beard_ice",
		"wilson_beard_lunar",
		"wilson_beard_madscience",
		"wilson_beard_magma",
		"wilson_beard_masquerade",
		"wilson_beard_nature",
		"wilson_beard_pigguard",
		"wilson_beard_pirate",
		"wilson_beard_rose",
		"wilson_beard_shadow",
		"wilson_beard_spring",
		"wilson_beard_survivor",
		"wilson_beard_victorian",
		"wilson_beard_yule",
	},
	winch =
	{
		"winch_pirate",
	},
	winona =
	{
		"winona_ancient",
		"winona_combatant",
		"winona_cook",
		"winona_factory",
		"winona_formal",
		"winona_formalp",
		"winona_frankenstein",
		"winona_gladiator",
		"winona_grassgecko",
		"winona_grassgecko_d",
		"winona_grassgecko_p",
		"winona_ice",
		"winona_lunar",
		"winona_magma",
		"winona_masquerade",
		"winona_nature",
		"winona_none",
		"winona_pirate",
		"winona_rose",
		"winona_rosep",
		"winona_shadow",
		"winona_shadowp",
		"winona_spring",
		"winona_survivor",
		"winona_survivorp",
		"winona_victorian",
		"winona_wrestler",
		"winona_yule",
	},
	winona_battery_high =
	{
		"winonabattery_high_fancy",
		"winonabattery_high_spike",
	},
	winona_battery_high_item =
	{
		"winonabattery_high_item_fancy",
		"winonabattery_high_item_spike",
	},
	winona_battery_low =
	{
		"winonabattery_low_fancy",
		"winonabattery_low_spike",
	},
	winona_battery_low_item =
	{
		"winonabattery_low_item_fancy",
		"winonabattery_low_item_spike",
	},
	winona_catapult =
	{
		"winona_catapult_fancy",
		"winona_catapult_spike",
	},
	winona_catapult_item =
	{
		"winona_catapult_item_fancy",
		"winona_catapult_item_spike",
	},
	winona_spotlight =
	{
		"winona_spotlight_fancy",
		"winona_spotlight_spike",
	},
	winona_spotlight_item =
	{
		"winona_spotlight_item_fancy",
		"winona_spotlight_item_spike",
	},
	winterhat =
	{
		"winterhat_black_davys",
		"winterhat_fancy_puppy",
		"winterhat_fancy_puppyalt",
		"winterhat_pink_hibiscus",
		"winterhat_plum_pudding",
		"winterhat_rooster",
		"winterhat_rooster_alt",
		"winterhat_stocking_cap_green_forest",
		"winterhat_western",
	},
	winterometer =
	{
		"winterometer_circus",
		"winterometer_mystical",
	},
	wobybig =
	{
		"woby_big_baddog",
		"woby_big_baddog_lunar",
		"woby_big_baddog_shadow",
		"woby_big_ribbon",
		"woby_big_ribbon_lunar",
		"woby_big_ribbon_shadow",
	},
	wobysmall =
	{
		"pupington_woby_baddog",
		"pupington_woby_baddog_lunar",
		"pupington_woby_baddog_shadow",
		"pupington_woby_ribbon",
		"pupington_woby_ribbon_lunar",
		"pupington_woby_ribbon_shadow",
	},
	wolfgang =
	{
		"wolfgang_ancient",
		"wolfgang_combatant",
		"wolfgang_cook",
		"wolfgang_formal",
		"wolfgang_formalp",
		"wolfgang_gladiator",
		"wolfgang_ice",
		"wolfgang_lunar",
		"wolfgang_magma",
		"wolfgang_nature",
		"wolfgang_none",
		"wolfgang_pirate",
		"wolfgang_rose",
		"wolfgang_rosep",
		"wolfgang_shadow",
		"wolfgang_shadowp",
		"wolfgang_strongman",
		"wolfgang_survivor",
		"wolfgang_survivorp",
		"wolfgang_victorian",
		"wolfgang_walrus",
		"wolfgang_walrus_d",
		"wolfgang_walrus_p",
		"wolfgang_wolfman",
		"wolfgang_wrestler",
		"wolfgang_yule",
	},
	wonkey =
	{
		"wonkey_none",
	},
	wood_chair =
	{
		"wood_chair_cawnival",
		"wood_chair_fantasy",
		"wood_chair_hallowed",
		"wood_chair_handmade",
		"wood_chair_western",
	},
	wood_stool =
	{
		"chair_stool_cawnival",
		"chair_stool_fantasy",
		"chair_stool_hallowed",
		"chair_stool_handmade",
		"chair_stool_western",
	},
	wood_table_round =
	{
		"round_table_cawnival",
		"round_table_fantasy",
		"round_table_hallowed",
		"round_table_handmade",
		"round_table_western",
	},
	wood_table_square =
	{
		"wood_table_cawnival",
		"wood_table_fantasy",
		"wood_table_hallowed",
		"wood_table_handmade",
		"wood_table_western",
	},
	woodcarvedhat =
	{
		"hat_woodcarved_swamp",
	},
	woodie =
	{
		"woodie_ancient",
		"woodie_combatant",
		"woodie_cook",
		"woodie_formal",
		"woodie_formalp",
		"woodie_gladiator",
		"woodie_hippie",
		"woodie_hockey",
		"woodie_ice",
		"woodie_lunar",
		"woodie_magma",
		"woodie_masquerade",
		"woodie_nature",
		"woodie_none",
		"woodie_pirate",
		"woodie_rose",
		"woodie_rosep",
		"woodie_shadow",
		"woodie_shadowp",
		"woodie_survivor",
		"woodie_survivorp",
		"woodie_treeguard",
		"woodie_treeguard_d",
		"woodie_treeguard_p",
		"woodie_victorian",
		"woodie_yule",
	},
	wormhole =
	{
		"wormhole_claw",
		"wormhole_fantasy",
		"wormhole_gothic",
		"wormhole_lureplant",
		"wormhole_spider",
		"wormhole_worm",
	},
	wormwood =
	{
		"wormwood_ancient",
		"wormwood_cactus",
		"wormwood_formal",
		"wormwood_ice",
		"wormwood_lunar",
		"wormwood_mushroom",
		"wormwood_nature",
		"wormwood_none",
		"wormwood_pumpkin",
		"wormwood_rose",
		"wormwood_saladmander",
		"wormwood_saladmander_d",
		"wormwood_saladmander_p",
		"wormwood_shadow",
		"wormwood_survivor",
		"wormwood_victorian",
		"wormwood_yule",
	},
	wortox =
	{
		"wortox_ancient",
		"wortox_dragon",
		"wortox_formal",
		"wortox_ice",
		"wortox_lunar",
		"wortox_masquerade",
		"wortox_minotaur",
		"wortox_nature",
		"wortox_noeyeddeer",
		"wortox_noeyeddeer_d",
		"wortox_noeyeddeer_p",
		"wortox_none",
		"wortox_original",
		"wortox_pirate",
		"wortox_rose",
		"wortox_shadow",
		"wortox_survivor",
		"wortox_victorian",
		"wortox_yule",
	},
	wurt =
	{
		"wurt_ancient",
		"wurt_cave",
		"wurt_formal",
		"wurt_ice",
		"wurt_lunar",
		"wurt_masquerade",
		"wurt_nature",
		"wurt_none",
		"wurt_pirate",
		"wurt_rose",
		"wurt_shadow",
		"wurt_squid",
		"wurt_survivor",
		"wurt_toadstool",
		"wurt_toadstool_d",
		"wurt_toadstool_p",
		"wurt_victorian",
		"wurt_yule",
	},
	wx78 =
	{
		"wx78_combatant",
		"wx78_cook",
		"wx78_formal",
		"wx78_formalp",
		"wx78_gladiator",
		"wx78_ice",
		"wx78_lunar",
		"wx78_magma",
		"wx78_masquerade",
		"wx78_nature",
		"wx78_none",
		"wx78_pirate",
		"wx78_retro",
		"wx78_rhinorook",
		"wx78_rhinorook_d",
		"wx78_rhinorook_p",
		"wx78_rose",
		"wx78_rosep",
		"wx78_shadow",
		"wx78_shadowp",
		"wx78_survivor",
		"wx78_survivorp",
		"wx78_victorian",
		"wx78_wip",
		"wx78_wrestler",
		"wx78_yule",
	},
	wx78_scanner =
	{
		"wx78_scanner_catcoon",
		"wx78_scanner_fancy",
		"wx78_scanner_junky",
	},
	wx78_scanner_item =
	{
		"wx78_scanner_catcoon_item",
		"wx78_scanner_fancy_item",
		"wx78_scanner_junky_item",
	},
	wx78_scanner_succeeded =
	{
		"wx78_scanner_succeeded_catcoon",
		"wx78_scanner_succeeded_fancy",
		"wx78_scanner_succeeded_junky",
	},
	yellowamulet =
	{
		"amulet_yellow_an",
		"amulet_yellow_flame",
		"amulet_yellow_ornate",
		"amulet_yellow_relic",
	},
	yellowstaff =
	{
		"starstaff_crystal",
		"starstaff_portal",
		"starstaff_relic",
		"starstaff_swamp",
	},

}

PREFAB_SKINS_SHOULD_NOT_SELECT = {
	["dragonflychest_upgraded_fantasy"] = true,
	["dragonflychest_upgraded_kraken"] = true,
	["treasurechest_upgraded_ancient"] = true,
	["treasurechest_upgraded_cake"] = true,
	["treasurechest_upgraded_carpetbag"] = true,
	["treasurechest_upgraded_clock"] = true,
	["treasurechest_upgraded_corruption"] = true,
	["treasurechest_upgraded_cotl_basic"] = true,
	["treasurechest_upgraded_cotl_fancy"] = true,
	["treasurechest_upgraded_crimson"] = true,
	["treasurechest_upgraded_cupid"] = true,
	["treasurechest_upgraded_gingerbread"] = true,
	["treasurechest_upgraded_monster"] = true,
	["treasurechest_upgraded_posh"] = true,
	["treasurechest_upgraded_poshprint"] = true,
	["treasurechest_upgraded_sacred"] = true,
	["treasurechest_upgraded_steamertrunk"] = true,
	["treasurechest_upgraded_traincase"] = true,
	["treasurechest_upgraded_traveltrunk"] = true,
	["treasurechest_upgraded_vintage"] = true,
}


PREFAB_SKINS_IDS = {}
for prefab,skins in pairs(PREFAB_SKINS) do
	PREFAB_SKINS_IDS[prefab] = {}
	for k,v in pairs(skins) do
		PREFAB_SKINS_IDS[prefab][v] = k
	end
end
