return {
  version = "1.1",
  luaversion = "5.1",
  orientation = "orthogonal",
  width = 30,
  height = 30,
  tilewidth = 64,
  tileheight = 64,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "../../../../tools/tiled/dont_starve/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "../../../../tools/tiled/dont_starve/tiles.png",
      imagewidth = 512,
      imageheight = 512,
      properties = {},
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 30,
      height = 30,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 52, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 52, 52, 52, 0, 0, 0, 52, 52, 0, 0, 0, 0, 0, 0, 52, 52, 52, 52, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 52, 52, 52, 52, 0, 52, 52, 52, 52, 0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 0, 0, 0, 0,
        0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 0, 0,
        0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0,
        0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 0,
        0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 52, 52, 52, 52, 52, 52, 52, 0,
        0, 0, 52, 52, 52, 52, 52, 52, 52, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0,
        0, 0, 52, 52, 52, 52, 52, 52, 52, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0,
        0, 0, 0, 52, 52, 52, 52, 52, 52, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0,
        0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0,
        0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0,
        0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 52, 52, 52, 52, 0,
        0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 52, 52, 52, 52, 0,
        0, 0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 52, 52, 52, 0,
        0, 0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0,
        0, 0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0,
        0, 0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0,
        0, 0, 0, 0, 52, 52, 52, 52, 52, 52, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 0,
        0, 0, 0, 0, 52, 52, 52, 52, 52, 52, 0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 0, 0,
        0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 0, 52, 52, 52, 52, 52, 52, 52, 52, 0, 52, 52, 52, 52, 52, 0, 0, 0, 0,
        0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 0, 52, 52, 52, 52, 52, 0, 0, 0,
        0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 52, 52, 52, 52, 52, 52, 0, 0,
        0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0,
        0, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0,
        0, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 0, 0,
        0, 0, 52, 52, 52, 52, 52, 0, 0, 0, 0, 0, 0, 52, 52, 52, 52, 52, 52, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 52, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          name = "",
          type = "shadowthrall_centipede_spawner",
          shape = "rectangle",
          x = 1017,
          y = 915,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1300,
          y = 913,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1326,
          y = 1005,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1398,
          y = 675,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1486,
          y = 551,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1626,
          y = 685,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1718,
          y = 857,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1724,
          y = 987,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1628,
          y = 1463,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1660,
          y = 1557,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1556,
          y = 1595,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1454,
          y = 1391,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1360,
          y = 1261,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1548,
          y = 1141,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1410,
          y = 1127,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 912,
          y = 1227,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1046,
          y = 1319,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 876,
          y = 1395,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 979,
          y = 1392,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1106,
          y = 1547,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1246,
          y = 1569,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1392,
          y = 1625,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1162,
          y = 1661,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1004,
          y = 1653,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 912,
          y = 1569,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 874,
          y = 1721,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 798,
          y = 1619,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 748,
          y = 1491,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 610,
          y = 1391,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 496,
          y = 1493,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 336,
          y = 1551,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 278,
          y = 1687,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 154,
          y = 1617,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 214,
          y = 1495,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 304,
          y = 1413,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 426,
          y = 1373,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 334,
          y = 1221,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 516,
          y = 1181,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 392,
          y = 1053,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 602,
          y = 1065,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 492,
          y = 1015,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 594,
          y = 903,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 308,
          y = 933,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 432,
          y = 865,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 548,
          y = 771,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 328,
          y = 781,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 446,
          y = 725,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 250,
          y = 667,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 358,
          y = 617,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 460,
          y = 465,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 222,
          y = 523,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 294,
          y = 413,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 448,
          y = 225,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 580,
          y = 303,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 746,
          y = 333,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 890,
          y = 231,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1034,
          y = 175,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1316,
          y = 237,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1452,
          y = 329,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1624,
          y = 405,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1276,
          y = 559,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1046,
          y = 449,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 818,
          y = 479,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 872,
          y = 373,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1006,
          y = 315,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 440,
          y = 343,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1208,
          y = 1233,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1278,
          y = 741,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 1148,
          y = 539,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_rock",
          shape = "rectangle",
          x = 722,
          y = 599,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1286,
          y = 1155,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1456,
          y = 1237,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1448,
          y = 1507,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1626,
          y = 1067,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1500,
          y = 713,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1596,
          y = 575,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1722,
          y = 447,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1464,
          y = 431,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1374,
          y = 543,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 936,
          y = 509,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 658,
          y = 715,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 290,
          y = 1103,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 448,
          y = 1279,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 392,
          y = 1469,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 240,
          y = 1589,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 398,
          y = 1641,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 616,
          y = 1489,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 850,
          y = 1485,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1116,
          y = 103,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1180,
          y = 209,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 954,
          y = 399,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 536,
          y = 387,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 452,
          y = 581,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 326,
          y = 519,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 336,
          y = 311,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 172,
          y = 403,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 228,
          y = 829,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 800,
          y = 1179,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 1502,
          y = 1049,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "tree_rock",
          shape = "rectangle",
          x = 732,
          y = 523,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 258,
          y = 285,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 210,
          y = 351,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 276,
          y = 491,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 382,
          y = 393,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 404,
          y = 531,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 518,
          y = 289,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 656,
          y = 363,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 682,
          y = 281,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 832,
          y = 311,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 992,
          y = 243,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1088,
          y = 275,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1372,
          y = 325,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1548,
          y = 381,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1708,
          y = 343,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1580,
          y = 487,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1498,
          y = 637,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1302,
          y = 647,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1040,
          y = 541,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 834,
          y = 571,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 348,
          y = 711,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 402,
          y = 957,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 312,
          y = 871,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 428,
          y = 1161,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 528,
          y = 1107,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 520,
          y = 927,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 290,
          y = 1347,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 526,
          y = 1423,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 308,
          y = 1493,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 906,
          y = 1649,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1022,
          y = 1555,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1082,
          y = 1433,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 954,
          y = 1341,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1550,
          y = 1441,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1350,
          y = 1561,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1488,
          y = 1643,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1552,
          y = 1519,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1526,
          y = 1319,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1630,
          y = 1149,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1636,
          y = 863,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1614,
          y = 767,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1362,
          y = 765,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1198,
          y = 625,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 708,
          y = 1123,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1122,
          y = 1251,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1272,
          y = 1081,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1034,
          y = 1139,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1136,
          y = 987,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1186,
          y = 843,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1040,
          y = 721,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 830,
          y = 765,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 746,
          y = 921,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 860,
          y = 1069,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 1160,
          y = 1127,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_fern_withered",
          shape = "rectangle",
          x = 924,
          y = 655,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 1156,
          y = 733,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "retrofit_fumaroleteleporter",
          shape = "rectangle",
          x = 177,
          y = 263,
          width = 0,
          height = 0,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 875,
          y = 892,
          width = 50,
          height = 50,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 275,
          y = 617,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 295,
          y = 374,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 117,
          y = 318,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 99,
          y = 259,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 179,
          y = 312,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 226,
          y = 322,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 274,
          y = 228,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 185,
          y = 190,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 138,
          y = 222,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 97,
          y = 176,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 97,
          y = 392,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 526,
          y = 183,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 582,
          y = 229,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 932,
          y = 326,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1100,
          y = 397,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1270,
          y = 241,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1422,
          y = 1013,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 324,
          y = 1049,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 284,
          y = 1235,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 386,
          y = 1342,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1514,
          y = 1175,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1612,
          y = 1403,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1273,
          y = 1675,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1100,
          y = 1640,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 333,
          y = 1656,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 120,
          y = 1589,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 579,
          y = 1345,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 626,
          y = 1017,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 1750,
          y = 944,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 1668,
          y = 522,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 1450,
          y = 281,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 1216,
          y = 1192,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_triple_withered",
          shape = "rectangle",
          x = 1690,
          y = 1667,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 442,
          y = 821,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 231,
          y = 772,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 404,
          y = 913,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 624,
          y = 1179,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 388,
          y = 1149,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 292,
          y = 1279,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 237,
          y = 1448,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 752,
          y = 1593,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 975,
          y = 1813,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 1086,
          y = 1670,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 956,
          y = 1523,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 1576,
          y = 765,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 1794,
          y = 530,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 1445,
          y = 517,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_double_withered",
          shape = "rectangle",
          x = 1564,
          y = 333,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1412,
          y = 398,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1569,
          y = 306,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "flower_cave_withered",
          shape = "rectangle",
          x = 1742,
          y = 533,
          width = 17,
          height = 16,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_mite_spawner",
          shape = "rectangle",
          x = 450,
          y = 650,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_mite_spawner",
          shape = "rectangle",
          x = 984,
          y = 1434,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        },
        {
          name = "",
          type = "cave_vent_mite_spawner",
          shape = "rectangle",
          x = 1230,
          y = 664,
          width = 68,
          height = 66,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
